trigger:
- master
 
pool:
  vmImage: "windows-latest"
 
steps:
- checkout: self
  displayName: "Checkout repository including submodules"
  submodules: true
 
- task: HugoTask@1
  inputs:
    source: 
    destination: '$(Build.ArtifactStagingDirectory)/Website'
 
- task: PublishPipelineArtifact@0
  displayName: "Publish deployment artifact"
  inputs:
    artifactName: "Deployment"
    targetPath: "$(Build.ArtifactStagingDirectory)"
