name: CI Workflow

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      - name: Clean public directory
        run: rm -rf public

      - name: Build
        run: hugo

      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: public/

      - name: Upload new files to Azure Blob Storage
        uses: bacongobbler/azure-blob-storage-upload@v1.2.0
        with:
          source_dir: "public"
          container_name: "$web"
          connection_string: ${{ secrets.STORAGEACCOUNTCONNECTIONSTRING }}
          sync: true
          overwrite: 'true'

      - name: Azure service principal login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURECREDENTIALSCDNMANAGER }}

      - name: Purge CDN
        run: az cdn endpoint purge -n ${{ secrets.AZURE_CDN_ENDPOINT }} --profile-name ${{ secrets.AZURE_CDN_PROFILE_NAME }} --content-paths "/*" --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}

      - name: Azure service principal logout
        run: az logout
