name: CI Workflow

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
            hugo-version: 'latest'

      - name: Clean public directory
        run: rm -rf public

      - name: Build
        run: hugo

      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: public/
